# Generated by Django 6.0.3 on 2026-03-15 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_complated',
            new_name='is_completed',
        ),
    ]
