# Generated by Django 6.0.3 on 2026-03-16 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_category_todo_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='priority',
            field=models.CharField(blank=True, choices=[('low', 'low'), ('medium', 'medium'), ('high', 'high')], default='medium', max_length=10, null=True),
        ),
    ]
