# Generated by Django 6.0.3 on 2026-03-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todo_deadline_todo_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
